name: '@zju-health-report/action Demo'

on:
  workflow_dispatch:
  schedule:
    # `0 23 * * *` 表示UTC 23:00，即北京时间7:00打卡（经测试，实际运行时间比设定时间晚几分钟到几十分钟）。
    - cron: '0 22 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - username: ZJU_USERNAME
            password: ZJU_PASSWORD
    steps:
      - name: 打卡
        uses: zju-health-report/action@release
        with:
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
        env:
      # 注意一定要在私有仓库里面才加这个，不然会 log 是公开的，会暴露你的隐私信息
          NODE_ENV: development
